### ISSUE TITLE
Uncaught Error: Status 'Refreshing targets for ~/OneDrive\Desktop\work\cppdoc' is already set

### ISSUE THREAD

**Issue by ravi1997** [steelbrain/busy-signal#71] opened 2019-09-30 15:25 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [busy-signal](https://github.com/steelbrain/busy-signal) package 2.0.1

### Stack Trace

Uncaught Error: Status 'Refreshing targets for C:\Users\ravi1\OneDrive\Desktop\work\cppdoc' is already set

```
At C:\Users\ravi1\.atom\packages\busy-signal\lib\registry.js:53

Error: Status 'Refreshing targets for C:\Users\ravi1\OneDrive\Desktop\work\cppdoc' is already set
    at Registry.statusAdd (/packages/busy-signal/lib/registry.js:53:13)
    at /packages/busy-signal/lib/registry.js:31:12
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1210649)
    at Provider.add (/packages/busy-signal/lib/provider.js:23:18)
    at TargetManager.refreshTargets (/packages/build/lib/target-manager.js:57:44)
    at TargetManager.selectActiveTarget (/packages/build/lib/target-manager.js:183:12)
    at /packages/build/lib/target-manager.js:23:82)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:349123)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1249835)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1245969)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:284329)
```

### Commands

```
     -2:26.9.0 intentions:highlight (input.hidden-input)
     -2:26.5.0 core:save (input.hidden-input)
     -2:20.7.0 intentions:highlight (input.hidden-input)
 53x -2:20.3.0 editor:move-line-up (input.hidden-input)
     -2:17.7.0 editor:move-to-beginning-of-word (input.hidden-input)
     -2:17.1.0 core:move-down (input.hidden-input)
     -2:16.7.0 editor:newline (input.hidden-input)
     -2:16.4.0 core:move-up (input.hidden-input)
     -2:15.9.0 editor:newline (input.hidden-input)
  8x -2:13.2.0 core:backspace (input.hidden-input)
     -2:06.8.0 intentions:highlight (input.hidden-input)
     -2:06.5.0 core:save (input.hidden-input)
     -1:17.6.0 core:confirm (input.hidden-input)
  7x -0:12.8.0 build:select-active-target (input.hidden-input)
     -0:06.1.0 editor:consolidate-selections (input.hidden-input)
     -0:06.1.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-cpp-template-foldings 0.1.4 
autocomplete-clang 0.12.0 
build 0.70.0 
build-make 0.13.0 
busy-signal 2.0.1 
gcc-make-run 0.2.12 
ide-flex-bison 1.2.1 
intentions 1.1.5 
language-bison-flex 0.3.1 
language-cpp14 0.6.2 
linter 2.3.1 
linter-clang-tidy 0.2.0 
linter-gcc 0.7.1 
linter-gcc2 0.8.7 
linter-ui-default 1.8.0 
remote-atom 1.3.12 
tool-bar 1.1.12 
```

**Comment by Arcanemagus** [comment] 2019-09-30 16:55
Please file this on the [`build` package](https://github.com/noseglid/atom-build/issues): they are attempting to add the same status more than once, which isn't allowed by the API. If you want this to get fixed please file an issue over there.

**Comment by Arcanemagus** [comment] 2019-09-30 16:55
Duplicate of #44

**Closed by Arcanemagus** 2019-09-30 16:55 UTC
