### ISSUE TITLE
Uncaught Error: Status 'Refreshing targets for D:/Coding\Python-Challenges\Pascal\test' is alread...

### ISSUE THREAD

**Issue by CrudeXD** [steelbrain/busy-signal#54] opened 2018-05-16 19:42 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [busy-signal](https://github.com/steelbrain/busy-signal) package 1.4.3

### Stack Trace

Uncaught Error: Status 'Refreshing targets for D:\Coding\Python-Challenges\Pascal\test' is already set

```
At C:\Users\orton\.atom\packages\busy-signal\lib\registry.js:50

Error: Status 'Refreshing targets for D:\Coding\Python-Challenges\Pascal\test' is already set
    at Registry.statusAdd (/packages/busy-signal/lib/registry.js:50:13)
    at /packages/busy-signal/lib/registry.js:31:12
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Provider.add (/packages/busy-signal/lib/provider.js:21:18)
    at TargetManager.refreshTargets (/packages/build/lib/target-manager.js:57:44)
    at TargetManager.getTargets (/packages/build/lib/target-manager.js:220:19)
    at Object.startNewBuild (/packages/build/lib/build.js:111:40)
    at /packages/build/lib/build.js:270:14
    at saveAndContinue (/packages/build/lib/build.js:277:7)
    at Object.doSaveConfirm (/packages/build/lib/build.js:281:7)
    at Object.build (/packages/build/lib/build.js:264:10)
    at /packages/build/lib/build.js:25:69)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.27.0/resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.27.0/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
  3x -5:07.0 editor:newline (input.hidden-input)
     -4:58.3.0 core:save (input.hidden-input)
     -4:57.1.0 settings-view:open (input.hidden-input)
  2x -4:49.8.0 core:confirm (input.hidden-input)
     -2:11.2.0 editor:newline (input.hidden-input)
     -2:04.8.0 core:move-left (input.hidden-input)
     -2:02.1.0 core:backspace (input.hidden-input)
  2x -2:00.0 core:move-right (input.hidden-input)
     -1:58.1.0 core:save (input.hidden-input)
  2x -1:55.7.0 build:trigger (input.hidden-input)
 13x -1:17.4.0 core:backspace (input.hidden-input)
     -1:11.9.0 core:confirm (input.hidden-input)
     -1:01.7.0 core:delete (input.hidden-input)
     -1:01.2.0 core:confirm (input.hidden-input)
     -0:08.8.0 build:trigger (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-ide-ui 0.11.2 
atom-python-run 0.9.6 
autocomplete-python 1.10.5 
build 0.70.0 
build-fpc 0.1.1 
busy-signal 1.4.3 
file-icons 2.1.20 
ide-python 0.9.2 
language-pascal 0.20.6 
minimap 4.29.8 
python-autopep8 0.1.3 
```

**Comment by Arcanemagus** [comment] 2018-05-16 22:50
Duplicate of #44

**Closed by Arcanemagus** 2018-05-16 22:50 UTC
