### ISSUE TITLE
Uncaught Error: Status 'Refreshing targets for D:/Users\Administrator\Documents\Julia\Julia-1.2.0...

### ISSUE THREAD

**Issue by ramsfa** [steelbrain/busy-signal#73] opened 2019-12-02 23:28 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Unknown Windows version
**Thrown From**: [busy-signal](https://github.com/steelbrain/busy-signal) package 2.0.1

### Stack Trace

Uncaught Error: Status 'Refreshing targets for D:\Users\Administrator\Documents\Julia\Julia-1.2.0\project_exam' is already set

```
At D:\Users\Administrator\Documents\Julia\.atom\packages\busy-signal\lib\registry.js:53

Error: Status 'Refreshing targets for D:\Users\Administrator\Documents\Julia\Julia-1.2.0\project_exam' is already set
    at Registry.statusAdd (/packages/busy-signal/lib/registry.js:53:13)
    at /packages/busy-signal/lib/registry.js:31:12
    at Function.simpleDispatch (D:/Users/Administrator/Documents/Julia/app-1.40.1/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (D:/Users/Administrator/Documents/Julia/app-1.40.1/resources/app/static/<embedded>:11:1210649)
    at Provider.add (/packages/busy-signal/lib/provider.js:23:18)
    at TargetManager.refreshTargets (/packages/build/lib/target-manager.js:57:44)
    at TargetManager.getTargets (/packages/build/lib/target-manager.js:220:19)
    at Object.startNewBuild (/packages/build/lib/build.js:111:40)
    at /packages/build/lib/build.js:270:14
    at saveAndContinue (/packages/build/lib/build.js:277:7)
    at Object.doSaveConfirm (/packages/build/lib/build.js:281:7)
    at Object.build (/packages/build/lib/build.js:264:10)
    at /packages/build/lib/build.js:25:69)
    at CommandRegistry.handleCommandEvent (D:/Users/Administrator/Documents/Julia/app-1.40.1/resources/app/static/<embedded>:11:349123)
    at CommandRegistry.dispatch (D:/Users/Administrator/Documents/Julia/app-1.40.1/resources/app/static/<embedded>:11:347598)
    at AtomEnvironment.dispatchApplicationMenuCommand (D:/Users/Administrator/Documents/Julia/app-1.40.1/resources/app/static/<embedded>:1:744892)
    at EventEmitter.t (D:/Users/Administrator/Documents/Julia/app-1.40.1/resources/app/static/<embedded>:1:752815)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
     -7:37.7.0 julia-client:copy-or-interrupt (textarea.xterm-helper-textarea)
  2x -7:36.1.0 ink-terminal:paste (textarea.xterm-helper-textarea)
     -6:39 julia-client:run-all (textarea.xterm-helper-textarea)
     -5:21.3.0 build:trigger (input.hidden-input)
     -4:02.5.0 julia-client:settings (input.hidden-input)
  2x -3:50.6.0 core:backspace (input.hidden-input)
     -2:33.6.0 project-manager:save-project (input.hidden-input)
     -1:46 core:confirm (input.hidden-input)
 34x -1:43.3.0 core:backspace (input.hidden-input)
     -0:22.2.0 build:trigger (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
build 0.70.0 
build-powershell 0.11.0 
busy-signal 2.0.1 
default-language 0.3.1 
ide-powershell 0.1.0 
ink 0.10.12 
julia-client 0.9.4 
language-julia 0.19.1 
language-powershell 5.0.0 
latex-completions 0.3.6 
project-manager 3.3.7 
tool-bar 1.1.12 
```

**Comment by Arcanemagus** [comment] 2019-12-23 18:39
Please file this on the [`build` package](https://github.com/noseglid/atom-build/issues): they are attempting to add the same status more than once, which isn't allowed by the API. If you want this to get fixed please file an issue over there.

**Comment by Arcanemagus** [comment] 2019-12-23 18:39
Duplicate of #44

**Closed by Arcanemagus** 2019-12-23 18:39 UTC
