### ISSUE TITLE
Uncaught Error: Status 'Refreshing targets for D:/didi\EspEasy\ESPEasy-mega\ESPEasy-mega' is alre...

### ISSUE THREAD

**Issue by TaiJiGong** [steelbrain/busy-signal#68] opened 2019-05-17 05:50 UTC
[Enter steps to reproduce:]

1. Startup Atom with Platformio
2. Start build
3. crach after some minutes
4. Startup again ...

**Atom**: 1.37.0 ia32
**Electron**: 2.0.18
**OS**: AINOL-MINI
**Thrown From**: [busy-signal](https://github.com/steelbrain/busy-signal) package 2.0.1

### Stack Trace

Uncaught Error: Status 'Refreshing targets for D:\didi\EspEasy\ESPEasy-mega\ESPEasy-mega' is already set

```
At C:\Users\didi\.atom\packages\busy-signal\lib\registry.js:53

Error: Status 'Refreshing targets for D:\didi\EspEasy\ESPEasy-mega\ESPEasy-mega' is already set
    at Registry.statusAdd (/packages/busy-signal/lib/registry.js:53:13)
    at /packages/busy-signal/lib/registry.js:31:12
    at Function.simpleDispatch (C:/Users/didi/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:1174290)
    at Emitter.emit (C:/Users/didi/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:1175731)
    at Provider.add (/packages/busy-signal/lib/provider.js:23:18)
    at TargetManager.refreshTargets (/packages/build/lib/target-manager.js:57:44)
    at emitNone (events.js:106:13)
    at CustomFile.emit (events.js:208:7)
    at /packages/build/lib/atom-build.js:84:89)
    at emitTwo (events.js:126:13)
    at FSWatcher.emit (events.js:214:7)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1368:12)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-clang 0.11.5 
build 0.70.0 
busy-signal 2.0.1 
file-icons 2.1.32 
intentions 1.1.5 
language-ini 1.20.0 
linter 2.3.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-ide 2.3.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.9.1 
tool-bar 1.1.11 
```

**Comment by Arcanemagus** [comment] 2019-05-20 22:52
Please file this on the [`build` package](https://github.com/noseglid/atom-build/issues): they are attempting to add the same status more than once, which isn't allowed by the API. If you want this to get fixed please file an issue over there.

**Comment by Arcanemagus** [comment] 2019-05-20 22:52
Duplicate of #44

**Closed by Arcanemagus** 2019-05-20 22:52 UTC
