### ISSUE TITLE
Uncaught Error: Status 'Refreshing targets for /home/arne/Docker/rgbdri' is already set

### ISSUE THREAD

**Issue by aosterthun** [steelbrain/busy-signal#57] opened 2018-06-11 22:27 UTC
```
Error: Status 'Refreshing targets for /home/arne/Docker/rgbdri' is already set
    at Registry.statusAdd (/home/arne/.atom/packages/busy-signal/lib/registry.js:50:13)
    at /home/arne/.atom/packages/busy-signal/lib/registry.js:31:12
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Provider.add (/home/arne/.atom/packages/busy-signal/lib/provider.js:21:18)
    at TargetManager.refreshTargets (/home/arne/.atom/packages/build/lib/target-manager.js:57:44)
    at TargetManager.getTargets (/home/arne/.atom/packages/build/lib/target-manager.js:220:19)
    at Object.startNewBuild (/home/arne/.atom/packages/build/lib/build.js:111:40)
    at /home/arne/.atom/packages/build/lib/build.js:270:14
    at saveAndContinue (/home/arne/.atom/packages/build/lib/build.js:277:7)
    at Object.doSaveConfirm (/home/arne/.atom/packages/build/lib/build.js:281:7)
    at Object.build (/home/arne/.atom/packages/build/lib/build.js:264:10)
    at HTMLElement.<anonymous> (/home/arne/.atom/packages/build/lib/build.js:25:69)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1347:25)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:339:53)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

**Comment by Arcanemagus** [comment] 2018-06-11 22:37
Please file this on the [build package](https://github.com/noseglid/atom-build/issues) they are attempting to add the same status more than once, which isn't allowed by the API.

**Comment by Arcanemagus** [comment] 2018-06-11 22:37
Duplicate of #44.

**Closed by Arcanemagus** 2018-06-11 22:37 UTC
