### ISSUE TITLE
Uncaught Error: Status 'Refreshing targets for ~/Desktop\BetterChairs-master' is already set

### ISSUE THREAD

**Issue by AlexFlipnote** [steelbrain/busy-signal#75] opened 2019-12-22 14:03 UTC
[Enter steps to reproduce:]

1. Edit `*.gradle` file
2. Save the file

**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [busy-signal](https://github.com/steelbrain/busy-signal) package 2.0.1

### Stack Trace

Uncaught Error: Status 'Refreshing targets for C:\Users\AlexFlipnote\Desktop\BetterChairs-master' is already set

```
At C:\Users\AlexFlipnote\.atom\packages\busy-signal\lib\registry.js:53

Error: Status 'Refreshing targets for C:\Users\AlexFlipnote\Desktop\BetterChairs-master' is already set
    at Registry.statusAdd (/packages/busy-signal/lib/registry.js:53:13)
    at /packages/busy-signal/lib/registry.js:31:12
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:1211760)
    at Emitter.emit (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:1213201)
    at Provider.add (/packages/busy-signal/lib/provider.js:23:18)
    at TargetManager.refreshTargets (/packages/build/lib/target-manager.js:57:44)
    at GradleBuildProvider.emit (events.js:182:13)
    at /packages/build-gradle/lib/gradle.js:74:16)
    at FSWatcher.emit (events.js:182:13)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:130:12)
```

### Commands

```
     -1:39.9.0 core:copy (input.hidden-input)
     -1:39.6.0 core:close (input.hidden-input)
     -1:37.5.0 editor:newline (input.hidden-input)
     -1:35.8.0 autocomplete-plus:confirm (input.hidden-input)
     -1:34.1.0 intentions:highlight (input.hidden-input)
     -1:34.1.0 core:paste (input.hidden-input)
     -1:33.6.0 intentions:highlight (input.hidden-input)
     -1:33.5.0 core:save (input.hidden-input)
  2x -1:26.5.0 core:backspace (input.hidden-input)
     -1:25.9.0 intentions:highlight (input.hidden-input)
     -1:25.6.0 core:save (input.hidden-input)
  2x -0:23.9.0 editor:newline (input.hidden-input)
     -0:23.6.0 intentions:highlight (input.hidden-input)
     -0:23.6.0 core:paste (input.hidden-input)
     -0:23.2.0 intentions:highlight (input.hidden-input)
     -0:23.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-discord 2.0.2 
atom-html-preview 0.2.6 
atom-ide-ui 0.13.0 
auto-indent 0.5.0 
bracket-colorizer 1.4.0 
build 0.70.0 
build-gradle 0.6.0 
busy-signal 2.0.1 
google-dark-syntax 3.3.0 
ide-css 0.3.3 
ide-python 1.5.0 
indent-guide-improved 1.4.13 
intentions 1.1.5 
language-batch 0.4.0 
language-kotlin 0.5.0 
linter 2.3.1 
linter-flake8 2.4.0 
linter-jshint 3.1.18 
linter-kotlin 0.6.0 
linter-scss-lint 3.2.1 
linter-ui-default 1.8.0 
pigments 0.40.2 
remote-ftp 2.2.2 
sort-lines 0.19.0 
standard-formatter 2.8.0 
teletype 0.13.4 
wakatime 7.1.2 
```

**Comment by Arcanemagus** [comment] 2019-12-23 18:39
Please file this on the [`build` package](https://github.com/noseglid/atom-build/issues): they are attempting to add the same status more than once, which isn't allowed by the API. If you want this to get fixed please file an issue over there.

**Comment by Arcanemagus** [comment] 2019-12-23 18:39
Duplicate of #44

**Closed by Arcanemagus** 2019-12-23 18:39 UTC
