### ISSUE TITLE
Uncaught Error: Status 'Refreshing targets for ~/Desktop\atom test' is already set

### ISSUE THREAD

**Issue by steliosot** [steelbrain/busy-signal#61] opened 2018-10-04 12:47 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.1 x64
**Electron**: 2.0.7
**OS**: Microsoft Windows 10 Enterprise 2016 LTSB
**Thrown From**: [busy-signal](https://github.com/steelbrain/busy-signal) package 1.4.3

### Stack Trace

Uncaught Error: Status 'Refreshing targets for C:\Users\stelios\Desktop\atom test' is already set

```
At C:\Users\stelios\.atom\packages\busy-signal\lib\registry.js:50

Error: Status 'Refreshing targets for C:\Users\stelios\Desktop\atom test' is already set
    at Registry.statusAdd (/packages/busy-signal/lib/registry.js:50:13)
    at /packages/busy-signal/lib/registry.js:31:12
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Provider.add (/packages/busy-signal/lib/provider.js:21:18)
    at TargetManager.refreshTargets (/packages/build/lib/target-manager.js:57:44)
    at TargetManager.getTargets (/packages/build/lib/target-manager.js:220:19)
    at Object.startNewBuild (/packages/build/lib/build.js:111:40)
    at /packages/build/lib/build.js:270:14
    at saveAndContinue (/packages/build/lib/build.js:277:7)
    at Object.doSaveConfirm (/packages/build/lib/build.js:281:7)
    at Object.build (/packages/build/lib/build.js:264:10)
    at /packages/build/lib/build.js:25:69)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.31.1/resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.31.1/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.31.1/resources/app/src/atom-environment.js:1351:25)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.31.1/resources/app/src/application-delegate.js:311:53)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -2:07.5.0 application:open-folder (input.hidden-input)
  2x -2:00.0 build:trigger (input.hidden-input)
```

### Non-Core Packages

```
build 0.70.0 
build-python 0.9.3 
busy-signal 1.4.3 
```

**Comment by Arcanemagus** [comment] 2018-10-04 15:45
Please file this on the [`build` package](https://github.com/noseglid/atom-build/issues): they are attempting to add the same status more than once, which isn't allowed by the API.

**Comment by Arcanemagus** [comment] 2018-10-04 15:46
Duplicate of #44

**Closed by Arcanemagus** 2018-10-04 15:46 UTC
