### ISSUE TITLE
Uncaught Error: Status 'Refreshing targets for ~/Desktop\Trabajos con ATOM\FPGAs\Obi T3' is alrea...

### ISSUE THREAD

**Issue by ea7kb** [steelbrain/busy-signal#65] opened 2019-02-21 19:01 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Unknown Windows version
**Thrown From**: [busy-signal](https://github.com/steelbrain/busy-signal) package 2.0.0

### Stack Trace

Uncaught Error: Status 'Refreshing targets for C:\Users\LEONARDO\Desktop\Trabajos con ATOM\FPGAs\Obi T3' is already set

```
At C:\Users\LEONARDO\.atom\packages\busy-signal\lib\registry.js:53

Error: Status 'Refreshing targets for C:\Users\LEONARDO\Desktop\Trabajos con ATOM\FPGAs\Obi T3' is already set
    at Registry.statusAdd (/packages/busy-signal/lib/registry.js:53:13)
    at /packages/busy-signal/lib/registry.js:31:12
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1172318)
    at Emitter.emit (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1173759)
    at Provider.add (/packages/busy-signal/lib/provider.js:23:18)
    at TargetManager.refreshTargets (/packages/build/lib/target-manager.js:57:44)
    at TargetManager.getTargets (/packages/build/lib/target-manager.js:220:19)
    at Object.startNewBuild (/packages/build/lib/build.js:111:40)
    at /packages/build/lib/build.js:270:14
    at saveAndContinue (/packages/build/lib/build.js:277:7)
    at Object.doSaveConfirm (/packages/build/lib/build.js:281:7)
    at Object.build (/packages/build/lib/build.js:264:10)
    at /packages/build/lib/build.js:64:62)
    at emitOne (events.js:116:13)
    at TargetManager.emit (events.js:211:7)
    at /packages/build/lib/target-manager.js:114:127)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:350017)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:348492)
    at ToolBarButtonView.executeCallback (/packages/tool-bar/lib/tool-bar-button-view.js:130:21)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/tool-bar-button-view.js:109:12)
```

### Commands

```
 14x -9:11.6.0 intentions:highlight (input.hidden-input)
     -9:10.6.0 core:save (input.hidden-input)
     -8:07.3.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -8:02.6.0 core:confirm (input.hidden-input)
     -7:58.7.0 core:paste (div.highlights)
     -7:54 intentions:highlight (input.hidden-input)
     -7:53.6.0 core:save (input.hidden-input)
     -2:35 tree-view:add-file (div.header.list-item.project-root-header)
     -2:26.7.0 core:confirm (input.hidden-input)
     -2:18.4.0 core:paste (div.highlights)
     -1:52.4.0 tree-view:move (span.name.icon.default-icon)
  3x -1:39.2.0 core:backspace (input.hidden-input)
     -1:32 core:confirm (input.hidden-input)
     -1:26.4.0 intentions:highlight (input.hidden-input)
     -1:26.3.0 core:save (input.hidden-input)
     -0:51 apio-ide:target:sim (input.hidden-input)
```

### Non-Core Packages

```
apio-ide 0.7.0 
apio-linter-verilog 0.7.2 
atom-beautify 0.33.4 
autocomplete-clang 0.11.5 
build 0.70.0 
busy-signal 2.0.0 
file-icons 2.1.30 
framer-syntax 1.1.0 
intentions 1.1.5 
language-ini 1.20.0 
language-pcf 0.2.0 
language-verilog 0.4.0 
linter 2.3.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
lunar-particle-ui 0.3.13 
platformio-ide 2.3.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.9.1 
tl-verilog 0.4.0 
tool-bar 1.1.11 
```

**Comment by Arcanemagus** [comment] 2019-02-21 19:31
Please file this on the [`build` package](https://github.com/noseglid/atom-build/issues): they are attempting to add the same status more than once, which isn't allowed by the API. If you want this to get fixed please file an issue over there.

**Comment by Arcanemagus** [comment] 2019-02-21 19:31
Duplicate of #44

**Closed by Arcanemagus** 2019-02-21 19:31 UTC
