### ISSUE TITLE
Uncaught Error: Status 'Refreshing targets for C:/Marlin\Marlin-BF20-SKR11-04072019' is already set

### ISSUE THREAD

**Issue by DavidThijs** [steelbrain/busy-signal#72] opened 2019-10-01 22:56 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 7 Ultimate 
**Thrown From**: [busy-signal](https://github.com/steelbrain/busy-signal) package 2.0.1

### Stack Trace

Uncaught Error: Status 'Refreshing targets for C:\Marlin\Marlin-BF20-SKR11-04072019' is already set

```
At C:\Users\David\.atom\packages\busy-signal\lib\registry.js:53

Error: Status 'Refreshing targets for C:\Marlin\Marlin-BF20-SKR11-04072019' is already set
    at Registry.statusAdd (/packages/busy-signal/lib/registry.js:53:13)
    at /packages/busy-signal/lib/registry.js:31:12
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1210649)
    at Provider.add (/packages/busy-signal/lib/provider.js:23:18)
    at TargetManager.refreshTargets (/packages/build/lib/target-manager.js:57:44)
    at TargetManager.getTargets (/packages/build/lib/target-manager.js:220:19)
    at Object.startNewBuild (/packages/build/lib/build.js:111:40)
    at /packages/build/lib/build.js:270:14
    at saveAndContinue (/packages/build/lib/build.js:277:7)
    at Object.doSaveConfirm (/packages/build/lib/build.js:281:7)
    at Object.build (/packages/build/lib/build.js:264:10)
    at /packages/build/lib/build.js:64:62)
    at TargetManager.emit (events.js:182:13)
    at /packages/build/lib/target-manager.js:114:127)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:349123)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:347598)
    at Object.runAtomCommand (/packages/platformio-ide/lib/utils.js:52:24)
    at /packages/platformio-ide/lib/main.js:258:30)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:349123)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:347598)
    at ToolBarButtonView.executeCallback (/packages/tool-bar/lib/tool-bar-button-view.js:134:21)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/tool-bar-button-view.js:113:12)
```

### Commands

```
  2x -1:51.8.0 platformio-ide:home (div.tool-panel.tree-view)
     -0:37.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax-dark.theme-electric-ui)
     -0:31.9.0 platformio-ide:target:build (div.tool-panel.tree-view)
     -0:31.9.0 platformio-ide:target:build-C:\Marlin\Marlin-BF2.0.x-SKR11-30092019\Marlin (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax-dark.theme-electric-ui)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
autocomplete-clang 0.12.0 
build 0.70.0 
busy-signal 2.0.1 
compare-files 0.8.1 
contrast-ui 0.53.0 
electric-ui 0.1.0 
file-icons 2.1.33 
git-clone 0.2.0 
intentions 1.1.5 
language-ini 1.21.0 
linter 2.3.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
monokai 0.24.0 
platformio-ide 2.4.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.9.1 
process-palette 0.17.0 
pure-syntax 1.0.1 
tool-bar 1.1.12 
```

**Comment by Arcanemagus** [comment] 2019-10-01 23:16
Please file this on the [`build` package](https://github.com/noseglid/atom-build/issues): they are attempting to add the same status more than once, which isn't allowed by the API. If you want this to get fixed please file an issue over there.

**Comment by Arcanemagus** [comment] 2019-10-01 23:16
Duplicate of #44

**Closed by Arcanemagus** 2019-10-01 23:16 UTC
