### ISSUE TITLE
Uncaught Error: Status 'Refreshing targets for ~/Desktop/libpistache-github' is already set

### ISSUE THREAD

**Issue by arthurafarias** [steelbrain/busy-signal#64] opened 2019-02-21 03:28 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Ubuntu 18.04.2
**Thrown From**: [busy-signal](https://github.com/steelbrain/busy-signal) package 2.0.0

### Stack Trace

Uncaught Error: Status 'Refreshing targets for /home/arthur/Desktop/libpistache-github' is already set

```
At /home/arthur/.atom/packages/busy-signal/lib/registry.js:53

Error: Status 'Refreshing targets for /home/arthur/Desktop/libpistache-github' is already set
    at Registry.statusAdd (/packages/busy-signal/lib/registry.js:53:13)
    at /packages/busy-signal/lib/registry.js:31:12
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1190133)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1191574)
    at Provider.add (/packages/busy-signal/lib/provider.js:23:18)
    at TargetManager.refreshTargets (/packages/build/lib/target-manager.js:57:44)
    at TargetManager.getTargets (/packages/build/lib/target-manager.js:220:19)
    at Object.startNewBuild (/packages/build/lib/build.js:111:40)
    at /packages/build/lib/build.js:270:14
    at saveAndContinue (/packages/build/lib/build.js:277:7)
    at Object.doSaveConfirm (/packages/build/lib/build.js:281:7)
    at Object.build (/packages/build/lib/build.js:264:10)
    at /packages/build/lib/build.js:25:69)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:350055)
    at Object.didConfirmSelection (/usr/share/atom/resources/app/static/<embedded>:11:692958)
    at SelectListView.confirmSelection (/usr/share/atom/resources/app/static/<embedded>:11:858391)
    at HTMLDivElement.core:confirm (/usr/share/atom/resources/app/static/<embedded>:11:853270)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:350055)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:1230760)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1226894)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:285234)
```

### Commands

```
     -1:31.1.0 command-palette:toggle (div.incompatible-packages.padded.native-key-bindings)
     -1:28.8.0 core:move-down (input.hidden-input)
     -1:28.2.0 core:confirm (input.hidden-input)
     -1:28.2.0 settings-view:install-packages-and-themes (div.incompatible-packages.padded.native-key-bindings)
  2x -1:25.2.0 core:backspace (input.hidden-input)
     -1:19.9.0 core:save (input.hidden-input)
     -0:55.4.0 core:select-all (input.hidden-input)
     -0:55.3.0 core:backspace (input.hidden-input)
     -0:36.3.0 core:close (input.hidden-input)
     -0:34.4.0 command-palette:toggle (input.hidden-input)
  3x -0:32.9.0 core:move-down (input.hidden-input)
     -0:32.1.0 core:move-up (input.hidden-input)
     -0:31.9.0 core:confirm (input.hidden-input)
     -0:31.9.0 build:trigger (input.hidden-input)
```

### Non-Core Packages

```
autocomplete 0.47.0 
autocomplete-clang 0.11.5 
build 0.70.0 
build-cmake 0.12.0 
busy-signal 2.0.0 
dbg 1.6.3 
dbg-gdb 1.7.8 
highlight-selected 0.14.0 
intentions 1.1.5 
linter 2.3.0 
linter-clang 4.1.2 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.2.1 
minimap-pigments 0.2.2 
output-panel 0.3.4 
```

**Comment by Arcanemagus** [comment] 2019-02-21 19:30
Please file this on the [`build` package](https://github.com/noseglid/atom-build/issues): they are attempting to add the same status more than once, which isn't allowed by the API. If you want this to get fixed please file an issue over there.

**Comment by Arcanemagus** [comment] 2019-02-21 19:31
Duplicate of #44

**Closed by Arcanemagus** 2019-02-21 19:31 UTC
